<a href="https://colab.research.google.com/github/rishik0910/data-mining/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [3]:
df = pd.read_csv("/content/titanic.csv")

In [4]:
df['Age'].fillna(df['Age'].median(), inplace=True)

<ipython-input-4-63d4fb902a4f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [5]:
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

<ipython-input-5-808ebb813aa0>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [6]:
df.drop(columns=['Cabin'], inplace=True)

In [7]:
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['Embarked'] = label_encoder.fit_transform(df['Embarked'])

In [8]:
df.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)

In [9]:
scaler = MinMaxScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

In [10]:
print("Processed Dataset:")
print(df.head())

Processed Dataset:
   Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         0       3    1  0.271174      1      0  0.014151         2
1         1       1    0  0.472229      1      0  0.139136         0
2         1       3    0  0.321438      0      0  0.015469         2
3         1       1    0  0.434531      1      0  0.103644         2
4         0       3    1  0.434531      0      0  0.015713         2

In [11]:
print(df)

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    1  0.271174      1      0  0.014151         2
1           1       1    0  0.472229      1      0  0.139136         0
2           1       3    0  0.321438      0      0  0.015469         2
3           1       1    0  0.434531      1      0  0.103644         2
4           0       3    1  0.434531      0      0  0.015713         2
..        ...     ...  ...       ...    ...    ...       ...       ...
886         0       2    1  0.334004      0      0  0.025374         2
887         1       1    0  0.233476      0      0  0.058556         2
888         0       3    0  0.346569      1      2  0.045771         2
889         1       1    1  0.321438      0      0  0.058556         0
890         0       3    1  0.396833      0      0  0.015127         1

[891 rows x 8 columns]

In [12]:
df

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    1  0.271174      1      0  0.014151         2
1           1       1    0  0.472229      1      0  0.139136         0
2           1       3    0  0.321438      0      0  0.015469         2
3           1       1    0  0.434531      1      0  0.103644         2
4           0       3    1  0.434531      0      0  0.015713         2
..        ...     ...  ...       ...    ...    ...       ...       ...
886         0       2    1  0.334004      0      0  0.025374         2
887         1       1    0  0.233476      0      0  0.058556         2
888         0       3    0  0.346569      1      2  0.045771         2
889         1       1    1  0.321438      0      0  0.058556         0
890         0       3    1  0.396833      0      0  0.015127         1

[891 rows x 8 columns]